export interface District {
  id: string
  name: string
}

export interface Taluka {
  id: string
  name: string
  district_id: string
}

export interface Village {
  id: string
  name: string
  taluka_id: string
}

export const mockDistricts: District[] = [
  { id: "1", name: "Mumbai" },
  { id: "2", name: "Pune" },
  { id: "3", name: "Nashik" },
  { id: "4", name: "Nagpur" },
  { id: "5", name: "Aurangabad" },
  { id: "6", name: "Solapur" },
  { id: "7", name: "Kolhapur" },
  { id: "8", name: "Sangli" },
  { id: "9", name: "Satara" },
  { id: "10", name: "Raigad" },
  { id: "11", name: "Thane" },
  { id: "12", name: "Ahmednagar" }
]

export const mockTalukas: Taluka[] = [
  // Mumbai District
  { id: "1", name: "Mumbai City", district_id: "1" },
  { id: "2", name: "Mumbai Suburban", district_id: "1" },
  { id: "3", name: "Kurla", district_id: "1" },
  
  // Pune District
  { id: "4", name: "Pune City", district_id: "2" },
  { id: "5", name: "Pimpri-Chinchwad", district_id: "2" },
  { id: "6", name: "Baramati", district_id: "2" },
  { id: "7", name: "Maval", district_id: "2" },
  { id: "8", name: "Shirur", district_id: "2" },
  
  // Nashik District
  { id: "9", name: "Nashik", district_id: "3" },
  { id: "10", name: "Malegaon", district_id: "3" },
  { id: "11", name: "Sinnar", district_id: "3" },
  { id: "12", name: "Dindori", district_id: "3" },
  
  // Nagpur District
  { id: "13", name: "Nagpur", district_id: "4" },
  { id: "14", name: "Kamptee", district_id: "4" },
  { id: "15", name: "Hingna", district_id: "4" },
  
  // Aurangabad District
  { id: "16", name: "Aurangabad", district_id: "5" },
  { id: "17", name: "Paithan", district_id: "5" },
  { id: "18", name: "Gangapur", district_id: "5" },
  
  // Other districts
  { id: "19", name: "Solapur", district_id: "6" },
  { id: "20", name: "Akkalkot", district_id: "6" },
  { id: "21", name: "Kolhapur", district_id: "7" },
  { id: "22", name: "Ichalkaranji", district_id: "7" },
  { id: "23", name: "Sangli", district_id: "8" },
  { id: "24", name: "Miraj", district_id: "8" },
  { id: "25", name: "Satara", district_id: "9" },
  { id: "26", name: "Karad", district_id: "9" },
  { id: "27", name: "Alibag", district_id: "10" },
  { id: "28", name: "Panvel", district_id: "10" },
  { id: "29", name: "Thane", district_id: "11" },
  { id: "30", name: "Kalyan-Dombivli", district_id: "11" },
  { id: "31", name: "Ahmednagar", district_id: "12" },
  { id: "32", name: "Shrirampur", district_id: "12" }
]

export const mockVillages: Village[] = [
  // Mumbai City Taluka
  { id: "1", name: "Colaba", taluka_id: "1" },
  { id: "2", name: "Fort", taluka_id: "1" },
  { id: "3", name: "Marine Lines", taluka_id: "1" },
  { id: "4", name: "Churchgate", taluka_id: "1" },
  
  // Mumbai Suburban Taluka
  { id: "5", name: "Bandra", taluka_id: "2" },
  { id: "6", name: "Andheri", taluka_id: "2" },
  { id: "7", name: "Juhu", taluka_id: "2" },
  { id: "8", name: "Borivali", taluka_id: "2" },
  
  // Pune City Taluka
  { id: "9", name: "Shivaji Nagar", taluka_id: "4" },
  { id: "10", name: "Kothrud", taluka_id: "4" },
  { id: "11", name: "Aundh", taluka_id: "4" },
  { id: "12", name: "Pune Cantonment", taluka_id: "4" },
  
  // Baramati Taluka
  { id: "13", name: "Baramati", taluka_id: "6" },
  { id: "14", name: "Morgaon", taluka_id: "6" },
  { id: "15", name: "Supa", taluka_id: "6" },
  { id: "16", name: "Jejuri", taluka_id: "6" },
  
  // Nashik Taluka
  { id: "17", name: "Nashik Road", taluka_id: "9" },
  { id: "18", name: "Gangapur Road", taluka_id: "9" },
  { id: "19", name: "Panchavati", taluka_id: "9" },
  { id: "20", name: "Dwarka", taluka_id: "9" },
  
  // Nagpur Taluka
  { id: "21", name: "Sitabuldi", taluka_id: "13" },
  { id: "22", name: "Dharampeth", taluka_id: "13" },
  { id: "23", name: "Sadar", taluka_id: "13" },
  { id: "24", name: "Itwari", taluka_id: "13" },
  
  // Add more villages for other talukas
  { id: "25", name: "Aurangabad Station", taluka_id: "16" },
  { id: "26", name: "CIDCO", taluka_id: "16" },
  { id: "27", name: "Solapur Central", taluka_id: "19" },
  { id: "28", name: "Railway Lines", taluka_id: "19" },
  { id: "29", name: "Kolhapur Station", taluka_id: "21" },
  { id: "30", name: "New Palace", taluka_id: "21" },
  { id: "31", name: "Sangli Miraj Road", taluka_id: "23" },
  { id: "32", name: "Market Yard", taluka_id: "23" },
  { id: "33", name: "Satara City", taluka_id: "25" },
  { id: "34", name: "Powai Naka", taluka_id: "25" },
  { id: "35", name: "Alibag Market", taluka_id: "27" },
  { id: "36", name: "Kihim Beach", taluka_id: "27" },
  { id: "37", name: "Thane Station", taluka_id: "29" },
  { id: "38", name: "Naupada", taluka_id: "29" },
  { id: "39", name: "Ahmednagar Camp", taluka_id: "31" },
  { id: "40", name: "Station Road", taluka_id: "31" }
]

// Mock farmer data for dropdowns
export const mockFarmers = [
  { id: "1", name: "Ramesh Patil", mobile: "9876543210" },
  { id: "2", name: "Suresh Sharma", mobile: "9876543211" },
  { id: "3", name: "Mahesh Jadhav", mobile: "9876543212" },
  { id: "4", name: "Ganesh Kulkarni", mobile: "9876543213" },
  { id: "5", name: "Rajesh Deshmukh", mobile: "9876543214" },
  { id: "6", name: "Prakash More", mobile: "9876543215" },
  { id: "7", name: "Santosh Pawar", mobile: "9876543216" },
  { id: "8", name: "Vinod Shinde", mobile: "9876543217" },
  { id: "9", name: "Anil Kale", mobile: "9876543218" },
  { id: "10", name: "Sachin Bhosale", mobile: "9876543219" }
]

// Mock land classification data
export const mockLandClassifications = [
  "Jirayat",
  "Bagayat", 
  "Parking",
  "Sarkaari",
  "Gairan",
  "Pan"
]

// Mock sub-classification data
export const mockSubClassifications = [
  "Paddy",
  "Wheat",
  "Sugarcane", 
  "Cotton",
  "Soybean",
  "Onion",
  "Tomato",
  "Grapes",
  "Mango",
  "Coconut"
]

// Helper functions to get filtered data
export const getTalukasByDistrict = (districtId: string): Taluka[] => {
  return mockTalukas.filter(taluka => taluka.district_id === districtId)
}

export const getVillagesByTaluka = (talukaId: string): Village[] => {
  return mockVillages.filter(village => village.taluka_id === talukaId)
}



// Auto-generated from PROMOLGATION.xlsx

export type PromulgationData = {
  [district: string]: {
    [taluka: string]: {
      [village: string]: boolean
    }
  }
};

export const promulgationData: PromulgationData = {
  Ahmedabad: {
    Mandal: {
      Anandapura: true,
      Ukardi: true,
      Udharozpur: true,
      Aydala: true,
      Odki: true,
      Kadvasan: true,
      Kunpur: true,
      Karshanpura: true,
      Kachrol: true,
      "Kanpura (Shi)": true,
      Jalisana: true,
      Jhanjarwa: true,
      Trent: true,
      Dadhana: true,
      Dhedhasana: true,
      Dalod: true,
      Navagam: true,
      "Small Ubhada": true,
      Nayakpur: true,
      Mandal: true,
      Manpura: true,
      Mithapur: true,
      Rakhiana: true,
      Ribdi: true,
      Vanapardi: true,
      Vermore: true,
      "Vasna Ku": true,
      Scorpion: true,
      Vitthalapur: true,
      Vinjuwada: true,
      Share: true,
      Shinj: true,
      Sadra: true,
      Sitapur: true,
      Solagam: true,
      "Hasalpur (B.)": true,
    },
    "Detroj-Rampura": {
      Abasana: true,
      Amarpura: true,
      Ashoknagar: true,
      Indrapura: true,
      Umaidpura: true,
      Odhav: true,
      Kukavav: true,
      Kanz: true,
      Kantrodi: true,
      Kointia: true,
      Gunjala: true,
      Gamanpura: true,
      Geetapur: true,
      Dhatisana: true,
      Dhelda: true,
      Chhaniyar: true,
      Jethipura: true,
      Jaspura: true,
      Dangarwa: true,
      Dabhasar: true,
      Dekawada: true,
      Detroj: true,
      Damodaripura: true,
      Nadishala: true,
      Nathpura: true,
      "Nana Karanpura": true,
      "Nani Rantai": true,
      Panar: true,
      Fatehpura: true,
      Bantai: true,
      Baramoli: true,
      Bosca: true,
      Bhankoda: true,
      Bhagapura: true,
      Bhoyani: true,
      Bhoyanipura: true,
      Madrisana: true,
      Marusana: true,
      "Big Karanpura": true,
      Badirantai: true,
      Ratanpura: true,
      Rudatal: true,
      Rajpura: true,
      "Vasna (Chhaniyar)": true,
      Shihor: true,
      Shobhasan: true,
      Sangpura: true,
      Sujapura: true,
      Sadatpura: true,
      Suvaula: true,
      Hathipura: true,
    },
    Viramgam: {
      Asalgam: true,
      Ukhlod: true,
      Agan: false,
      Kumrakhan: true,
      Kamijala: false,
      Karkathal: false,
      Karangarh: true,
      Kariyala: true,
      Kankrawadi: true,
      Kadipur: true,
      "Kanpura (Ten)": true,
      Kayla: true,
      Kaliana: true,
      Kokta: true,
      Khegaria: true,
      Khudad: true,
      Goraya: true,
      Chanothia: true,
      Chuninapura: true,
      Jakshi: true,
      Jakhwada: true,
      Jaitapur: false,
      Junapaghar: true,
      Jalampura: true,
      Zezra: false,
      Dediasan: true,
      Dumana: true,
      Thuleta: true,
      Thorithambha: false,
      Thorimubarak: false,
      Thorivadgas: true,
      Devpura: true,
      Daslana: true,
      Dhakdi: true,
      Dhoda: false,
      Nadiana: true,
      "Little Kumad": true,
      "Nani kishol": true,
      Bhadana: true,
      Bhavda: true,
      Bhojwa: true,
      Memadpura: true,
      Melj: true,
      Bigkumad: true,
      "Moti kishol": false,
      Rangpur: true,
      Rupavati: true,
      Rahmalpur: true,
      Limbad: true,
      Leia: true,
      Vekaria: true,
      Vadagas: true,
      Vani: true,
      Vanathal: true,
      Valana: true,
      Vasavelia: true,
      Vessel: true,
      Vanswa: true,
      Viramgam: false,
      Shahpur: false,
      Shiyal: true,
      Shivpura: true,
      Sachana: false,
      Sabalpura: true,
      Sarasavadi: true,
      Sonkli: true,
      Hasalpur: true,
    },
    Sanand: {
      Andej: false,
      Aniyali: true,
      Iawa: false,
      Upland: true,
      Kundal: true,
      Kalana: false,
      Kunwar: false,
      Kaneti: true,
      Kodalia: true,
      Colt: false,
      Khicha: false,
      Khoda: true,
      Khorj: false,
      Garodia: true,
      Godhavi: false,
      Goraj: false,
      Govinda: true,
      Chekhla: false,
      Charal: true,
      Changodar: false,
      Chharodi: false,
      Juda: true,
      Juval: true,
      Jhampa: false,
      Jholapur: false,
      Daran: false,
      Telav: false,
      Tajpur: true,
      Daduka: false,
      Dodar: false,
      Navapura: true,
      "Nani Devati": true,
      Naranpura: true,
      Nidharad: false,
      Nothcourtpura: true,
      Palwada: false,
      Pimpan: false,
      Phangdi: true,
      Bakrana: false,
      Bol: true,
      Bhavanpur: true,
      Makhyav: false,
      Matoda: false,
      Manipur: true,
      Melasana: true,
      Mankol: false,
      "Big Devati": false,
      Modasar: false,
      Moraiya: false,
      Rethal: false,
      Rupavati: true,
      Rampura: true,
      Lekhamba: true,
      Lodariyal: false,
      Vanalia: true,
      Vasodara: true,
      "Vasna Iyawa": false,
      "Vasna Tea": false,
      Vichhiya: true,
      Virochannagar: false,
      Shella: false,
      Sheawada: true,
      Sanathal: false,
      Sari: true,
      "Sanand Village": false,
      Soyla: false,
      Hirapur: true,
    },
    Dashkroi: {
      Aslali: true,
      Istolabad: true,
      Undel: true,
      Anasan: true,
      Odd: true,
      Kunjad: true,
      Kathwara: true,
      Kanbha: true,
      Kubadthal: true,
      Kuha: true,
      Kaniyel: true,
      Kacinda: true,
      Gatrad: true,
      Garatnagar: true,
      Garatpur: true,
      Village: true,
      Girmatha: true,
      Govindada: true,
      Chavalaj: true,
      Chandiyel: true,
      Chaucer: true,
      Jetalpur: false,
      Zanu: true,
      Tiba: true,
      Devdi: true,
      Dhamatwan: true,
      Navrangpura: true,
      Navapura: true,
      Naz: true,
      Nandedez: true,
      Pardol: true,
      Pashuanj: true,
      "Paldi Kankaj": true,
      Badodara: true,
      "Bakrol Bujrang": true,
      Barjedi: true,
      Bareja: true,
      Bibipur: true,
      Bilacia: true,
      Bharkunda: true,
      Bhuwal: true,
      Bhuwaldi: true,
      Rice: true,
      Bhavda: true,
      Memadpur: true,
      Mahijada: true,
      Miroli: true,
      Ranodara: true,
      Ropra: true,
      Lalpur: true,
      Vadodara: true,
      Vasai: true,
      Bahalal: true,
      Read: true,
      Visalpur: true,
      Sigarwa: true,
      Huqa: true,
      Harniav: true,
      Hirapur: true,
    },
    Dholka: {
      Andhari: true,
      Arnej: true,
      Anandapura: true,
      Ambethi: true,
      Ambeliara: true,
      Ambereli: true,
      Ingoli: true,
      Utelia: true,
      Kariyana: true,
      Kalyanpur: true,
      Kesargarh: true,
      Kadipur: true,
      Kaliapara: true,
      Koth: true,
      Kouka: true,
      Kharanti: true,
      Bharashpur: true,
      Khanpur: true,
      Gundi: true,
      Ganesar: true,
      Ganol: true,
      Girand: true,
      Dholka: false,
      Dholi: true,
      Chandisar: false,
      Chaloda: true,
      "J. Godhaneshwar": true,
      "Jalalpur Wajifa": true,
      Jawaraj: true,
      Jakhada: true,
      Dadusar: true,
      Tarsanda: true,
      Nesda: true,
      Naniboru: true,
      Paldi: true,
      Pisawada: true,
      Begwa: true,
      Badarkha: false,
      Bhetawada: true,
      Bhubhali: true,
      Bhurkhi: true,
      Bholad: true,
      Munjpur: true,
      Maflipur: true,
      "Big Boru": true,
      Ranoda: true,
      Rupgarh: true,
      Rajpur: true,
      Rampur: true,
      Rampura: true,
      Raipur: true,
      Lana: true,
      Lolia: true,
      Vejalka: true,
      Vataman: true,
      Warana: true,
      Valthera: true,
      "Vasna Kelia": true,
      Virdi: true,
      Veerpur: true,
      Vautha: true,
      Shekhadi: true,
      Sheawada: true,
      Samani: true,
      Sargwala: false,
      Sarandhi: true,
      Saroda: false,
      Sahej: true,
      Sathal: true,
      Sindhrej: true,
      Simage: true,
    },
    Bawla: {
      Amipura: true,
      Adroda: true,
      Kerala: true,
      KALYANGADH: true,
      Kavla: true,
      KESRANDI: true,
      Canotar: true,
      Kaliveji: true,
      Kavitha: true,
      KOCHARIYA: true,
      Gundanapara: true,
      Gangad: true,
      CHIYADA: true,
      Chhabasar: true,
      "JUVAL - RUPAVATI": true,
      ZEKDA: true,
      Dhedhal: true,
      Dumli: true,
      Durgi: true,
      DevDholera: true,
      Devadthal: true,
      Dahegamda: true,
      Dhanwada: true,
      Dhingda: true,
      NANODARA: true,
      Bagodara: true,
      Baldana: true,
      Bavla: true,
      Bhamsara: true,
      Bhayla: true,
      METAL: true,
      MENI: true,
      MEMAR: true,
      Mithapur: true,
      Rajoda: true,
      Rupal: true,
      Ranesar: true,
      Rasam: true,
      Rohika: true,
      Lagdana: true,
      "VASNA - NANODARA": true,
      "VASNA - DHEDHAL": true,
      Shiyal: true,
      SARALA: true,
      SANKOD: true,
      Sakodara: true,
      Saljada: true,
      HASANNAGAR: true,
    },
    Dhandhuka: {
      Adwal: true,
      "Ani Bhimji": true,
      Aakaru: true,
      High: true,
      Umargarh: true,
      Kotda: true,
      Kothadia: true,
      Khadol: true,
      Kharad: true,
      Khasta: true,
      Gunjar: true,
      Galsana: true,
      Dhandhuka: true,
      Chhasiyana: true,
      Chharodiya: true,
      Jashapar: true,
      Jaska: true,
      Jalia: true,
      Zanjarka: true,
      Zinzer: true,
      Tagadi: true,
      Dholi: true,
      Nanatradiya: true,
      Pacham: true,
      Padana: true,
      Parbadi: true,
      Pipal: true,
      Fatehpur: true,
      Fedra: true,
      Bajrada: true,
      Bhalgamda: true,
      Bigtradia: true,
      Morcia: true,
      Rangpur: true,
      Ratanpur: true,
      Raika: true,
      Rojka: true,
      Warr: true,
      Wagad: true,
      Vasna: true,
      Sarwal: true,
      Salasar: true,
      Hadala: true,
      Haripura: true,
    },
    Dholera: {
      Anandpur: true,
      Ambli: true,
      Otaria: true,
      Kamiyala: true,
      Kadipur: true,
      Kamatalaav: true,
      Kasindra: true,
      Khun: true,
      Gaff: true,
      Gogla: true,
      Gorasu: true,
      Dhanala: true,
      Dholera: true,
      Chair: true,
      Tableau: true,
      Navagam: true,
      Panchi: true,
      Pimpli: true,
      Buranpur: true,
      Bavaliyari: false,
      Bhadiyad: true,
      Bhangarh: true,
      Bhimtala: true,
      Mundi: true,
      Mahadevapura: true,
      Mingalpur: true,
      Rahatalaav: true,
      Walinda: true,
      Shella: true,
      Sangasar: true,
      Sandhida: true,
      Sodhi: true,
      Hebatpur: true,
    },
    Asarwa: {
      Asarwa: false,
      Kottarpur: false,
      "Dariapur Kazipur": false,
      Naroda: false,
      Nicole: false,
      Muthia: false,
      "Sejpur Bogha": false,
      Sardarnagar: false,
      Hanspura: false,
      Hansol: false,
    },
    Maninagar: {
      Isanpur: false,
      Khokhra: false,
      Ghodasar: false,
      "Dani Limda": false,
      Narol: false,
      Behrampura: false,
      "Bage Firdos": false,
      Mithipur: false,
      Rakhial: false,
      "Raj Heerpur": false,
      "City Kotda": false,
    },
    Vatva: {
      Odhav: false,
      Commode: false,
      Gyaspur: false,
      Pipalj: false,
      Ramol: false,
      Lakshmipura: false,
      Benefits: false,
      Vatva: false,
      Vastral: false,
      Vizonl: false,
      Shahwadi: false,
      "Saijpur Gopalpur": false,
      Hathijan: false,
    },
    Ghatlodia: {
      Ambli: false,
      Oganj: false,
      Khodiyar: false,
      Gota: false,
      Ghatlodia: false,
      Chainpur: false,
      Chharodi: false,
      Jagatpur: false,
      Tragad: false,
      Thaltej: false,
      Ghuma: false,
      Bodakdev: false,
      Bopal: false,
      Bhadaj: false,
      Memnagar: false,
      Lapakaman: true,
      Lilapur: true,
      Shilaj: false,
      Sola: false,
      Hebatpur: false,
    },
    Sabarmati: {
      Acher: false,
      Usmanpura: false,
      Black: false,
      Kochrab: false,
      Changijpur: false,
      Chandkheda: false,
      Chandlodia: false,
      Chhadavad: false,
      Paldi: false,
      Motera: false,
      Ranip: false,
      Vadaj: false,
      Vasna: false,
      Sheikha: false,
    },
    Vejalpur: {
      Auqaf: false,
      Jodhpur: false,
      Fatehwadi: false,
      "Bakrol  Badrabad": false,
      Badrabad: false,
      Maktampur: false,
      Makarba: false,
      Vejalpur: false,
      Banjar: false,
      Vastrapur: false,
      Sarkhej: false,
    },
  },
  Gandhinagar: {
    Kalol: {
      Adhana: true,
      Arsodia: true,
      Isand: true,
      Unali: true,
      Ushmanabad: true,
      Ola: true,
      Kantha: true,
      Karoli: true,
      Khatraj: true,
      Khorjadabhi: true,
      Ganpatpura: true,
      Golthara: true,
      Chhatral: true,
      Jethlaj: true,
      Jaspur: false,
      Dingucha: true,
      Dantali: true,
      Dhamasana: true,
      Dhanaj: true,
      Dhanot: true,
      New: true,
      Nandoli: true,
      Nardipur: true,
      NASMED: true,
      Pratappura: true,
      Palsana: true,
      Paliad: true,
      Palodia: true,
      Pansar: true,
      PYJ: true,
      Bileshwarpura: true,
      Borisana: true,
      Bhaupura: true,
      Bhadol: true,
      Bhimasan: true,
      "Basement Big": true,
      Mulasana: true,
      Mokhasan: true,
      Rakanpur: true,
      Ranchhodpura: true,
      Rancherda: true,
      Ramnagar: true,
      Vadsar: true,
      Veda: true,
      Vadavaswami: true,
      Waina: true,
      "Vansajada (a)": true,
      "Vansajada (Dhe)": true,
      Sherisa: true,
      Saij: false,
      Sanawad: true,
      Sabaspur: true,
      Santej: false,
      Hajipur: true,
    },
    Mansa: {
      Anodia: true,
      Ambod: true,
      "Amarpura (B)": true,
      Amrapur: true,
      Aluva: false,
      Ajol: true,
      Amja: true,
      Itala: true,
      Itadara: true,
      Indrapura: true,
      Kunwadara: true,
      Khadat: true,
      Kharana: true,
      "Sour Amba": true,
      "In Gun": true,
      Galthara: true,
      Gulabpura: true,
      Chadasana: true,
      Charadu: false,
      Charada: false,
      Chandisana: true,
      Jamla: true,
      Delwar: true,
      Delwara: true,
      Dhendhu: true,
      Dhameda: true,
      Dholakuwa: true,
      Nadri: true,
      Padusma: true,
      Pundhara: true,
      Parbatpura: false,
      Patanpura: true,
      Parsa: true,
      "Paldi (Rathod)": true,
      "Paldi (Diameter)": true,
      "Fatepura (Mother)": true,
      Badpura: true,
      Bapupura: false,
      Balwa: true,
      Bilodara: true,
      Boru: true,
      "Bhimpura (Mother)": true,
      "Mandali (V)": true,
      Mahudi: true,
      "Manekpura (Makakhad)": true,
      Manasa: false,
      Rangpur: true,
      "Rajpura (Mother)": true,
      "Rampura (Mother)": true,
      Retrol: true,
      Lakarora: true,
      Libodra: true,
      Lodara: true,
      Veda: true,
      Versova: true,
      Vagosana: true,
      Vihar: true,
      Samau: true,
      Swelling: true,
      Sobhasan: true,
      Solaiya: false,
      "Harna Hoda": true,
    },
    Gandhinagar: {
      Adalaj: false,
      Ambapur: true,
      Amiyapur: false,
      "Respect is big": true,
      Adiwada: false,
      Alampur: true,
      Indroda: false,
      "Isanpur Big": true,
      Unawa: true,
      Uwarsad: true,
      Kudasan: false,
      Karai: true,
      Koteswar: true,
      Koba: false,
      Kolavada: false,
      Khorj: false,
      Galudan: true,
      Geod: true,
      Chekhlarani: true,
      Chandrala: true,
      "Chiloda (Dabhoda)": true,
      "Chiloda (Naroda)": false,
      Peela: true,
      Jamiyatpura: true,
      Jalud: true,
      Jakhora: true,
      Jhundal: false,
      Tintoda: true,
      Dabhoda: true,
      Tarapur: true,
      Dantali: true,
      Dashela: true,
      "Dolarana Vasana": true,
      Dhanap: true,
      Dholakuwa: false,
      Nabhoi: true,
      "New Dharampur": true,
      Pethapur: false,
      Pundrasana: true,
      Province: true,
      Palj: false,
      Pindhara: true,
      People: true,
      Pirojpur: true,
      Por: true,
      Basan: false,
      Borij: false,
      Bhat: false,
      "Bhoyan Rathod": true,
      Magodi: true,
      Medra: true,
      Mubarakpura: true,
      Mahundhara: true,
      Madhavgarh: true,
      Ranasar: false,
      Ratanpur: true,
      Rupal: true,
      Rajpur: true,
      Randeshana: false,
      Randheja: true,
      Raipur: true,
      Raisan: false,
      Lecawada: false,
      Lawarpur: true,
      Limbadiya: true,
      Vadodara: true,
      Valad: true,
      Wankanerda: true,
      Wavol: false,
      "Vasna Hadmatia": false,
      Vasan: true,
      "Veera Talavadi": true,
      Shertha: true,
      Shahpur: true,
      "Shiholi Big": true,
      Sughad: true,
      Sargasan: false,
      Saradhva: true,
      Sadra: true,
      Sonarda: true,
      Sonipur: true,
    },
    Dahegam: {
      Anguthala: true,
      Antoli: true,
      "Amraji's Muwada": true,
      "Arjanji's Muwada": true,
      Antroli: true,
      "Isanpur Dodiya": true,
      Example: true,
      Ahmadpura: true,
      Ottampura: true,
      Kadjodra: true,
      Kadadara: true,
      Kantharpura: true,
      Kanpur: true,
      "Kamaalbandha Vasana": true,
      Karoli: true,
      "Kalyanji's Muwada": true,
      Krishnanagar: true,
      Kodrali: true,
      Khakhra: true,
      Khadia: true,
      Khanpur: true,
      "Chekhla Pagi": true,
      "Chanda/Jesana Muwa": true,
      Chamla: true,
      Chiskari: true,
      "Jalundra Nana": true,
      "Jalundra Big": true,
      "Jalia Math": true,
      Jindwa: true,
      "Jivaji's Muwadi": true,
      Zanq: true,
      Dumecha: true,
      Demalia: true,
      Thadakuwa: true,
      "Devkaran's Muvada": true,
      Dahegam: true,
      Race: true,
      Dhamij: true,
      Dharisana: true,
      Najupura: true,
      Navanagar: true,
      Nandol: true,
      "Pallana Math": true,
      Pasuniya: true,
      Paharia: true,
      "Patna Well": true,
      Palundra: true,
      Palaiya: true,
      "People's": true,
      Badpur: true,
      Bahial: true,
      Babra: true,
      "Bardoli Baria": true,
      "Bardoli Kanthi": true,
      Baria: true,
      Billmana: true,
      Bhadroda: true,
      "Meghrajna Muwada": true,
      Mahudia: true,
      "Machhang Nani": true,
      "Machhang Big": true,
      "Salt Muwada": true,
      Mirzapur: true,
      Mirapur: true,
      "Big Pawdi": true,
      Motipura: true,
      "Morali Badi": true,
      Mausampur: true,
      Rakhiyal: true,
      Ramnagar: true,
      Lawad: true,
      Lihoda: true,
      Vatva: true,
      Vadvasa: true,
      Vadod: true,
      "Wardhana Muwada": true,
      Velpura: true,
      "Vasna Chaudhary": true,
      "Vasna Rathod": true,
      "Vasana Sogathi": true,
      Shiapura: true,
      Shiyavada: true,
      Sagadalpur: true,
      "Sujana Muwada": true,
      Salki: true,
      Sanoda: true,
      Sampa: true,
      Sambela: true,
      Oppositetri: true,
      "Sahebji's Muwada": true,
      "Harkhanji's Muwada": true,
      Harsoli: true,
      Hatijan: true,
      Halisa: true,
      Hillol: true,
      "Hilol Vasna": true,
    },
    "Kalol City": {
      Kalol: false,
    },
  },
  Mehsana: {
    Satlasana: {
      Ajbapur: true,
      Ankaliyara: true,
      "Anand Bhankhari": true,
      Ishaqpura: true,
      Umri: true,
      Umrecha: true,
      Otalpur: true,
      Kanedia: true,
      Kubda: true,
      Kevdasan: true,
      Kesharpura: true,
      Kazipur: true,
      "Kothasana Nana": true,
      "Kothasana Big": true,
      Khari: true,
      Khilod: true,
      Khodamli: true,
      Gamanpura: true,
      "Gamanpura (Hadol)": true,
      Galalpur: true,
      Gothada: true,
      Chelana: true,
      Chhelpura: true,
      Jashpuria: true,
      Jaspur: true,
      Timmba: true,
      Dhadhivas: true,
      Takhtpura: true,
      Talegarh: true,
      Dulana: true,
      Dharoi: true,
      Dharavania: true,
      Navavas: true,
      Nanibhalu: true,
      Nizampura: true,
      Nidardi: true,
      Pirojpura: true,
      Fatepura: true,
      Bedsma: true,
      Bhatwas: true,
      Bhanvas: true,
      Bhalusana: true,
      Bhimpur: true,
      Mumanavas: true,
      Malana: true,
      Malapur: true,
      Big: true,
      "Rangpur (Garh)": true,
      Rabarivas: true,
      "Rajpur (Garh)": true,
      Ranpur: true,
      Radhapura: true,
      Bears: true,
      Waghar: true,
      Wajapur: true,
      Vadnal: true,
      Vasai: true,
      Wadhwa: true,
      Vav: true,
      "Vavdi (Fort)": true,
      Vansda: true,
      Sheshpur: true,
      Shahupura: true,
      Satlasana: true,
      Sadrasana: true,
      Sudasana: true,
      Samarapur: true,
      Seymour: true,
      Sartanpura: true,
      Sardarpur: true,
      Santola: true,
      Hadol: true,
      Himatpura: true,
    },
    Kheralu: {
      Ambawada: true,
      Amarpura: true,
      Arathi: true,
      Kuda: true,
      Kheralu: true,
      Gathaman: true,
      Ghazipur: true,
      Gorisana: true,
      Chacharia: true,
      Chada: true,
      Chansol: true,
      Chotia: true,
      Dabhad: true,
      Dabhoda: true,
      Dalisana: true,
      Dawal: true,
      Thangana: true,
      Dedasana: true,
      Delwara: true,
      "Nandali (Miyasana)": true,
      "Naniwada (Kadarpur)": true,
      Nortol: true,
      Panchha: true,
      "Fatepura (Khe)": true,
      Balad: true,
      Machhwa: true,
      Mandali: true,
      Mandropur: true,
      "Malekpur (Khe)": true,
      Malarpura: true,
      Mahekubapura: true,
      Mahial: true,
      "Big Hirwani": true,
      Rasulpar: true,
      Rahmanpura: true,
      Lunwa: true,
      Lalawada: true,
      Limbdi: true,
      Waghwadi: true,
      Varetha: true,
      "Vavdi (Khe)": true,
      Vithoda: true,
      "Shahpur (Shantokpura)": true,
      "Century Kapoor": true,
      Samoja: true,
      Suvaria: true,
      Sakri: true,
      Sangthala: true,
    },
    UNJHA: {
      Amudh: true,
      Unawa: true,
      Upera: true,
      Unjha: true,
      Aithor: true,
      Kantravi: true,
      Karanpur: true,
      Karli: true,
      Kahoda: true,
      Kamli: true,
      Khatasana: true,
      Jagannathpura: true,
      Tundav: true,
      Dabhi: true,
      Dasaj: true,
      Navapura: true,
      Pali: true,
      Brahmanwada: true,
      Bhunaav: true,
      Bhankhar: true,
      Makatpur: true,
      Meherwada: true,
      Ranchhodpura: true,
      Lindi: true,
      Lihoda: true,
      Vanagala: true,
      Varwada: true,
      Vishol: true,
      Shihi: true,
      Sunak: true,
      Surpura: true,
      Hajipur: true,
    },
    Visnagar: {
      Iyasara: true,
      Udalpur: true,
      Umata: true,
      Kada: true,
      Kamana: true,
      Kuvasana: true,
      Kansarakui: true,
      Kazialiyasana: true,
      "Kamalpur (B)": true,
      "Kamalpur (Go)": true,
      Kansa: true,
      Kiadar: true,
      Khandosan: true,
      Khadalpur: true,
      Kharwada: true,
      Gunja: true,
      Gunjala: true,
      Ganpatpura: true,
      Arrangement: true,
      "Pictures big": true,
      Chitrodipura: true,
      "Short term": true,
      Jetalvasana: true,
      Tarabh: true,
      Thumthal: true,
      Thalota: true,
      Dadhiyal: true,
      Denap: true,
      Dhadharet: true,
      Dhamanwa: true,
      Dharusana: true,
      Pudgam: true,
      Paldi: true,
      Becharpura: true,
      Bakarpur: true,
      Basana: true,
      Bokarwada: true,
      Bhandu: true,
      Bhalak: true,
      Magroda: true,
      Mehmedpur: true,
      "Rangpur (Khe)": true,
      Rangakui: true,
      Randala: true,
      Rajgarh: true,
      Rampura: true,
      Ralysana: true,
      Rawalapura: true,
      Lakshmipura: true,
      Lachhi: true,
      Vadu: true,
      Valam: true,
      "Visnagar (Rural)": true,
      Saduthala: true,
      Question: true,
      Sunshi: true,
      Satusana: true,
      Hasanpur: true,
    },
    Vadnagar: {
      Anandpura: true,
      Aspa: true,
      Undni: true,
      Undhai: true,
      Unad: true,
      "Kamalpur (Vad)": true,
      Karbatiya: true,
      Karsanpura: true,
      Caseympa: true,
      Kahipur: true,
      Khatasana: true,
      Khatoda: true,
      Khanpur: true,
      Ganeshpura: true,
      Chandpur: true,
      Champa: true,
      Chhablia: true,
      Jagapur: true,
      "Old Wagdi": true,
      Jaska: true,
      Left: true,
      Transwad: true,
      Navapura: true,
      "New Wagdi": true,
      Pimpaldar: true,
      Bajpura: true,
      Badarpur: true,
      Babipura: true,
      Madhasan: true,
      "Malekpur (Vad)": true,
      Mirzapur: true,
      Molipur: true,
      "Rajpur (Vad)": true,
      Vaktapur: true,
      Vadnagar: true,
      Valasana: true,
      "Sheikhpur (Khe)": true,
      "Sheikhpur (Vad)": true,
      "Shahpur (Vad)": true,
      Shobhasan: true,
      Sundhia: true,
      Sabalpur: true,
      Sarna: true,
      "Sultanpur (Vad)": true,
      Sulipur: true,
      Sipor: true,
      Hajipur: true,
    },
    Vijapur: {
      Absana: true,
      "Ashnapur (Garita)": true,
      Aglod: true,
      Asoda: true,
      Ibharampura: true,
      Ubakhal: true,
      Kukarwada: true,
      Kanbha: true,
      Kamalpur: true,
      Calisana: true,
      Coat: true,
      Kotdi: true,
      Kolavada: true,
      Khanusa: true,
      Kharod: true,
      Gunchhi: true,
      Gadhada: true,
      Ganeshpura: true,
      Gundrasan: true,
      Garita: true,
      Gawada: true,
      Changod: true,
      Jantral: true,
      Jaipur: true,
      Techawa: true,
      Tintodan: true,
      Daria: true,
      Dabhala: true,
      Tatosan: true,
      Dagawadia: true,
      Devda: true,
      Devpura: true,
      "Dhanpura (Ghantu)": true,
      Pedhamli: true,
      Pamol: true,
      Pilwai: true,
      Fudeda: true,
      Flu: true,
      Bamanwa: true,
      Billia: true,
      "Bhimpur Valor": true,
      "Mandali Kharod": true,
      Malav: true,
      "Manekpur (Dabhala)": true,
      Malosan: true,
      Motipur: true,
      Morwad: true,
      Ranchhodpura: true,
      Ranasipur: true,
      Ranasan: true,
      "Ramupur (Kuwayda)": true,
      "Rampura (Kot)": true,
      Ladol: true,
      Vadasan: true,
      "Vasai (Dabhala)": true,
      Vijapur: true,
      Sunderpur: true,
      Sandhpur: true,
      Sayajinagar: true,
      Sardarpur: true,
      Sokhada: true,
      Swelling: true,
      Hathipura: true,
      Hirapura: true,
    },
    Mehsana: {
      Ambassan: true,
      Aloda: true,
      Akhaj: true,
      Ambaliyasan: true,
      "Ijpura (Barot)": true,
      Ucharpi: true,
      Cooks: true,
      Kadvasan: true,
      Karshanpura: true,
      Kochwa: true,
      Kherwa: true,
      Kharasda: true,
      Khara: true,
      Gadha: true,
      Gamanpura: true,
      Gartapur: true,
      Gilosan: true,
      Gozaria: true,
      Gorad: true,
      Dhandhusan: true,
      Dholasan: true,
      Charadu: true,
      Chaluva: true,
      Chitrodipura: true,
      Chhathiyarda: true,
      Jagudan: true,
      Jetalpur: true,
      "Old Shedhavi": true,
      Jamnapur: true,
      Jorang: true,
      Tundali: true,
      Taleti: true,
      Tawadia: true,
      Dediyasan: true,
      Dela: true,
      Deloli: true,
      Devrasan: true,
      Dawada: true,
      Devinapur: true,
      Ditasan: true,
      Diwanpura: true,
      Nugar: true,
      Nadasa: true,
      "New Shedhavi": true,
      Nagalpur: true,
      Nanidau: true,
      Padharia: true,
      Punasan: true,
      Panchot: true,
      Palj: true,
      Palavasana: true,
      Palodar: true,
      Piludara: true,
      Buttapaladi: true,
      Balol: true,
      Balwantpura: true,
      Bamosana: true,
      Baliasan: true,
      Bodla: true,
      Boriawi: true,
      Bhensana: true,
      Bhakadia: true,
      Bhasaria: true,
      Meu: true,
      Maguna: true,
      Mandali: true,
      Medhaaliyasana: true,
      Mareda: true,
      Mulasan: true,
      Mewd: true,
      Mehsana: true,
      Salt: true,
      Badidau: true,
      Rupal: true,
      "Rampura (Kukas)": true,
      Ramosan: true,
      Lakshmipura: true,
      Lakhwad: true,
      Langhnaj: true,
      Lynch: true,
      Vadasma: true,
      Vadosan: true,
      Bravery: true,
      Sakhapurda: true,
      Sanganpur: true,
      Front: true,
      Saldi: true,
      Sobhashan: true,
      "Heduwa (Rajgar)": true,
      "Heduwa (Hanumantha)": true,
      Hebuwa: true,
      Hardesan: true,
      Haripura: true,
      Hadvi: true,
      Higglajpura: true,
    },
    Becharaji: {
      Ajabpura: true,
      Ambala: true,
      Ankaba: true,
      Adiwada: true,
      Aszol: true,
      Indrap: true,
      Udela: true,
      Adala: true,
      Kakasana: true,
      Kanoda: true,
      Karansagar: true,
      Kalri: true,
      Khambhel: true,
      Ganeshpura: true,
      Gaambhu: true,
      Chadasan: true,
      Chandroda: true,
      Chandanki: true,
      Chhatasan: true,
      Jetpur: true,
      Dedana: true,
      Dodiwada: true,
      Dethali: true,
      Dedarda: true,
      "Delpura (Khant)": true,
      "Delwara (Khant)": true,
      Deogarh: true,
      Dhanpura: true,
      "Dharpura (Khant)": true,
      Pratapgarh: true,
      Poyda: true,
      Finchdi: true,
      Becher: true,
      Bariaf: true,
      Bhalgamda: true,
      Mandali: true,
      Matrasan: true,
      Motap: true,
      Modhera: true,
      Ranchhodpura: true,
      Ranela: true,
      "Rooppura Karanpura": true,
      "At night": true,
      Vanapur: true,
      Venpura: true,
      Vijapurda: true,
      Shankhalpur: true,
      Sujanpura: true,
      Saduthala: true,
      Suraj: true,
      Surpura: true,
      Sampawada: true,
    },
    KADI: {
      Acharasan: true,
      Ankhol: true,
      Adudara: true,
      Ambabapura: true,
      Aldesan: true,
      Agol: true,
      Adraj: true,
      Anandapura: true,
      Ambaliyara: true,
      Iran: true,
      Ishwarpura: true,
      Indrad: true,
      Camel: true,
      Umanagar: true,
      Kundal: true,
      "Kadi Kasba": true,
      Kanjri: true,
      Kyle: true,
      Karjisan: true,
      Karannagar: true,
      Karsanpura: true,
      Kalyanpura: true,
      Kaswa: true,
      Korda: true,
      Kolad: true,
      Khandamorwa: true,
      Khanderaopura: true,
      Kherpur: true,
      Khavad: true,
      Ganeshpura: true,
      Galodara: true,
      Govindpura: true,
      Ghughla: true,
      Ghumasan: true,
      Chadasana: true,
      Chandrasan: true,
      Chandarda: true,
      Charol: true,
      Jetpura: true,
      Jamiyatpura: true,
      Jesangpura: true,
      Jadavpura: true,
      Jasalpur: true,
      Jhulasan: true,
      Jhaloda: true,
      Tankia: true,
      Daran: true,
      "Daran Morva": true,
      Dangarwa: true,
      Dhoria: true,
      Thadod: true,
      Thol: true,
      Deusana: true,
      Dudhai: true,
      Della: true,
      Nagarasan: true,
      Nadan: true,
      Nandasan: true,
      Narsinghpura: true,
      Nadolia: true,
      Nanapurasanwad: true,
      "Small link": true,
      Naranpura: true,
      Narola: true,
      Panthoda: true,
      Palli: true,
      Pirojpur: true,
      Fatepura: true,
      Phuletra: true,
      Budasan: true,
      Balasar: true,
      Babajipura: true,
      Bavlu: true,
      Borisana: true,
      Bhalathi: true,
      Medha: true,
      Manipur: true,
      Merda: true,
      Maharajpura: true,
      Mathasur: true,
      Mokasan: true,
      Yeshwantpura: true,
      Rangpurda: true,
      Rajpur: true,
      Rozapuri: true,
      Laxmanpura: true,
      "Lakshmipura (A)": true,
      "Lakshmipura (Nandasan)": true,
      Lunasan: true,
      Lhor: true,
      Vekra: true,
      Vadu: true,
      Vadapura: true,
      Vadavi: true,
      Bansol: true,
      Varkhadia: true,
      Valavadi: true,
      Waghroda: true,
      Wamj: true,
      Vinayakpura: true,
      Visatpur: true,
      Visalpur: true,
      Vidj: true,
      Sujatpur: true,
      Sedfa: true,
      Sedardi: true,
      Sedarana: true,
      Sarasav: true,
      Sadra: true,
      Siyapura: true,
      Haripura: true,
    },
    Jotana: {
      Ajabpura: true,
      Alampur: true,
      "Ijpura (Jethaji)": true,
      Katosan: true,
      Kushalpura: true,
      Kanpura: true,
      Khadalpur: true,
      Gokalpura: true,
      Dhanali: true,
      Dhandhalpur: true,
      Dholasan: true,
      Chalasan: true,
      Chalesara: true,
      Jakasana: true,
      Jotana: true,
      Tejpura: true,
      Telawi: true,
      Digdi: true,
      Dhanpura: true,
      Balsasan: true,
      Bhatariya: true,
      Bhatasan: true,
      Mudarda: true,
      Memadpura: true,
      Martoli: true,
      Mankanaj: true,
      Modipur: true,
      Moyan: true,
      Ranipur: true,
      "Rampura (Katosan)": true,
      Virsoda: true,
      Suraj: true,
      Santhal: true,
      Sidosana: true,
      Harsundal: true,
    },
  },
};


// ----------- Utility functions --------------

export const getDistricts = (): string[] => Object.keys(promulgationData);

export const getTalukas = (district: string): string[] =>
  district && promulgationData[district] ? Object.keys(promulgationData[district]) : [];

export const getVillages = (district: string, taluka: string): string[] =>
  district && taluka && promulgationData[district]?.[taluka]
    ? Object.keys(promulgationData[district][taluka])
    : [];

    
export const isPromulgation = (
  district: string,
  taluka: string,
  village: string
): boolean | null => {
  if (
    district &&
    taluka &&
    village &&
    promulgationData[district]?.[taluka]?.[village] !== undefined
  ) {
    return promulgationData[district][taluka][village];
  }
  return null;
};
